/**
 * Generate `src/styles/payload-admin-generated.css`: one relative `@import` per Payload
 * admin stylesheet, so an admin document request carries a real <link> for the full
 * component CSS instead of relying on RSC-injected resources (which only exist after
 * client navigation).
 *
 * Bun-native: no `node:fs`. Output is byte-stable (sorted paths, content dedupe) so a
 * second run is a no-op; `tests/payload-admin-css.test.ts` pins the file set against these
 * same filters.
 */

export {}

const ROOTS = ['node_modules/@payloadcms/ui/dist', 'node_modules/@payloadcms/richtext-lexical/dist'] as const
const SKIPPED: Record<string, true> = {
  'node_modules/@payloadcms/ui/dist/styles.css': true,
  'node_modules/@payloadcms/ui/dist/css/app.css': true,
}

const OUTPUT = 'src/styles/payload-admin-generated.css'

/** `@import` specifiers must be relative: the vendored strip plugin nulls bare specifiers in `ssr`. */
function toSpecifier(repoRelativePath: string): string {
  return `../../${repoRelativePath}`
}

async function collect(): Promise<string[]> {
  const glob = new Bun.Glob('**/*.css')
  const paths: string[] = []
  for (const root of ROOTS) {
    for await (const entry of glob.scan({ cwd: root })) {
      const absolute = `${root}/${entry}`
      if (absolute.includes('/node_modules/')) continue
      if (SKIPPED[absolute]) continue
      paths.push(absolute)
    }
  }
  return paths
}

async function main(): Promise<void> {
  const candidates = (await collect()).sort((a, b) => (a < b ? -1 : 1))
  const seen = new Set<string>()
  const imports: string[] = []
  let totalBytes = 0

  for (const path of candidates) {
    const bytes = await Bun.file(path).arrayBuffer()
    const digest = new Bun.CryptoHasher('sha256').update(new Uint8Array(bytes)).digest('hex')
    if (seen.has(digest)) continue
    seen.add(digest)
    imports.push(`@import '${toSpecifier(path)}';`)
    totalBytes += bytes.byteLength
  }

  const header = '/* Generated by scripts/generate-payload-admin-css.ts. Do not edit by hand. */\n'
  await Bun.write(OUTPUT, header + imports.join('\n') + '\n')
  console.info(JSON.stringify({ event: 'payload.admin_css.generated', fileCount: imports.length, totalBytes }))
}

await main()
