/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PayloadRouteImport } from './routes/_payload'
import { Route as SiteRouteImport } from './routes/_site'
import { Route as HumansDottxtRouteImport } from './routes/humans[.txt]'
import { Route as LlmsFullDottxtRouteImport } from './routes/llms-full[.txt]'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.txt]'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.txt]'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.xml]'
import { Route as Char91DotwellKnownChar93SecurityChar91DottxtChar93RouteImport } from './routes/[.well-known]/security[.txt]'
import { Route as SiteIndexRouteImport } from './routes/_site.index'
import { Route as SiteAboutRouteImport } from './routes/_site.about'
import { Route as SiteChatRouteImport } from './routes/_site.chat'
import { Route as SiteContactRouteImport } from './routes/_site.contact'
import { Route as ApiSplatRouteImport } from './routes/api.$'
import { Route as PayloadAdminIndexRouteImport } from './routes/_payload.admin.index'
import { Route as PayloadAdminSplatRouteImport } from './routes/_payload.admin.$'
import { Route as SiteBlogIndexRouteImport } from './routes/_site.blog.index'
import { Route as SiteBlogSlugRouteImport } from './routes/_site.blog.$slug'
import { Route as SiteChangelogIndexRouteImport } from './routes/_site.changelog.index'
import { Route as SiteChangelogSlugRouteImport } from './routes/_site.changelog.$slug'
import { Route as SiteProjectsIndexRouteImport } from './routes/_site.projects.index'
import { Route as SiteProjectsSlugRouteImport } from './routes/_site.projects.$slug'
import { Route as ApiSiteChatRouteImport } from './routes/api.site.chat'
import { Route as ApiSiteContactRouteImport } from './routes/api.site.contact'
import { Route as ApiSiteHealthRouteImport } from './routes/api.site.health'

const PayloadRoute = PayloadRouteImport.update({
  id: '/_payload',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteRoute = SiteRouteImport.update({
  id: '/_site',
  getParentRoute: () => rootRouteImport,
} as any)
const HumansDottxtRoute = HumansDottxtRouteImport.update({
  id: '/humans.txt',
  path: '/humans.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsFullDottxtRoute = LlmsFullDottxtRouteImport.update({
  id: '/llms-full.txt',
  path: '/llms-full.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotwellKnownChar93SecurityChar91DottxtChar93Route =
  Char91DotwellKnownChar93SecurityChar91DottxtChar93RouteImport.update({
    id: '/.well-known/security.txt',
    path: '/.well-known/security.txt',
    getParentRoute: () => rootRouteImport,
  } as any)
const SiteIndexRoute = SiteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteAboutRoute = SiteAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => SiteRoute,
} as any)
const SiteChatRoute = SiteChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => SiteRoute,
} as any)
const SiteContactRoute = SiteContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => SiteRoute,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const PayloadAdminIndexRoute = PayloadAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => PayloadRoute,
} as any)
const PayloadAdminSplatRoute = PayloadAdminSplatRouteImport.update({
  id: '/admin/$',
  path: '/admin/$',
  getParentRoute: () => PayloadRoute,
} as any)
const SiteBlogIndexRoute = SiteBlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteBlogSlugRoute = SiteBlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => SiteRoute,
} as any)
const SiteChangelogIndexRoute = SiteChangelogIndexRouteImport.update({
  id: '/changelog/',
  path: '/changelog/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteChangelogSlugRoute = SiteChangelogSlugRouteImport.update({
  id: '/changelog/$slug',
  path: '/changelog/$slug',
  getParentRoute: () => SiteRoute,
} as any)
const SiteProjectsIndexRoute = SiteProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteProjectsSlugRoute = SiteProjectsSlugRouteImport.update({
  id: '/projects/$slug',
  path: '/projects/$slug',
  getParentRoute: () => SiteRoute,
} as any)
const ApiSiteChatRoute = ApiSiteChatRouteImport.update({
  id: '/api/site/chat',
  path: '/api/site/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSiteContactRoute = ApiSiteContactRouteImport.update({
  id: '/api/site/contact',
  path: '/api/site/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSiteHealthRoute = ApiSiteHealthRouteImport.update({
  id: '/api/site/health',
  path: '/api/site/health',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof SiteIndexRoute
  '/humans.txt': typeof HumansDottxtRoute
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.well-known/security.txt': typeof Char91DotwellKnownChar93SecurityChar91DottxtChar93Route
  '/about': typeof SiteAboutRoute
  '/chat': typeof SiteChatRoute
  '/contact': typeof SiteContactRoute
  '/api/$': typeof ApiSplatRoute
  '/admin/$': typeof PayloadAdminSplatRoute
  '/blog/$slug': typeof SiteBlogSlugRoute
  '/changelog/$slug': typeof SiteChangelogSlugRoute
  '/projects/$slug': typeof SiteProjectsSlugRoute
  '/api/site/chat': typeof ApiSiteChatRoute
  '/api/site/contact': typeof ApiSiteContactRoute
  '/api/site/health': typeof ApiSiteHealthRoute
  '/admin/': typeof PayloadAdminIndexRoute
  '/blog/': typeof SiteBlogIndexRoute
  '/changelog/': typeof SiteChangelogIndexRoute
  '/projects/': typeof SiteProjectsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof SiteIndexRoute
  '/humans.txt': typeof HumansDottxtRoute
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.well-known/security.txt': typeof Char91DotwellKnownChar93SecurityChar91DottxtChar93Route
  '/about': typeof SiteAboutRoute
  '/chat': typeof SiteChatRoute
  '/contact': typeof SiteContactRoute
  '/api/$': typeof ApiSplatRoute
  '/admin/$': typeof PayloadAdminSplatRoute
  '/blog/$slug': typeof SiteBlogSlugRoute
  '/changelog/$slug': typeof SiteChangelogSlugRoute
  '/projects/$slug': typeof SiteProjectsSlugRoute
  '/api/site/chat': typeof ApiSiteChatRoute
  '/api/site/contact': typeof ApiSiteContactRoute
  '/api/site/health': typeof ApiSiteHealthRoute
  '/admin': typeof PayloadAdminIndexRoute
  '/blog': typeof SiteBlogIndexRoute
  '/changelog': typeof SiteChangelogIndexRoute
  '/projects': typeof SiteProjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_payload': typeof PayloadRouteWithChildren
  '/_site': typeof SiteRouteWithChildren
  '/humans.txt': typeof HumansDottxtRoute
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.well-known/security.txt': typeof Char91DotwellKnownChar93SecurityChar91DottxtChar93Route
  '/_site/about': typeof SiteAboutRoute
  '/_site/chat': typeof SiteChatRoute
  '/_site/contact': typeof SiteContactRoute
  '/api/$': typeof ApiSplatRoute
  '/_site/': typeof SiteIndexRoute
  '/_payload/admin/$': typeof PayloadAdminSplatRoute
  '/_site/blog/$slug': typeof SiteBlogSlugRoute
  '/_site/changelog/$slug': typeof SiteChangelogSlugRoute
  '/_site/projects/$slug': typeof SiteProjectsSlugRoute
  '/api/site/chat': typeof ApiSiteChatRoute
  '/api/site/contact': typeof ApiSiteContactRoute
  '/api/site/health': typeof ApiSiteHealthRoute
  '/_payload/admin/': typeof PayloadAdminIndexRoute
  '/_site/blog/': typeof SiteBlogIndexRoute
  '/_site/changelog/': typeof SiteChangelogIndexRoute
  '/_site/projects/': typeof SiteProjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/humans.txt'
    | '/llms-full.txt'
    | '/llms.txt'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/.well-known/security.txt'
    | '/about'
    | '/chat'
    | '/contact'
    | '/api/$'
    | '/admin/$'
    | '/blog/$slug'
    | '/changelog/$slug'
    | '/projects/$slug'
    | '/api/site/chat'
    | '/api/site/contact'
    | '/api/site/health'
    | '/admin/'
    | '/blog/'
    | '/changelog/'
    | '/projects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/humans.txt'
    | '/llms-full.txt'
    | '/llms.txt'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/.well-known/security.txt'
    | '/about'
    | '/chat'
    | '/contact'
    | '/api/$'
    | '/admin/$'
    | '/blog/$slug'
    | '/changelog/$slug'
    | '/projects/$slug'
    | '/api/site/chat'
    | '/api/site/contact'
    | '/api/site/health'
    | '/admin'
    | '/blog'
    | '/changelog'
    | '/projects'
  id:
    | '__root__'
    | '/_payload'
    | '/_site'
    | '/humans.txt'
    | '/llms-full.txt'
    | '/llms.txt'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/.well-known/security.txt'
    | '/_site/about'
    | '/_site/chat'
    | '/_site/contact'
    | '/api/$'
    | '/_site/'
    | '/_payload/admin/$'
    | '/_site/blog/$slug'
    | '/_site/changelog/$slug'
    | '/_site/projects/$slug'
    | '/api/site/chat'
    | '/api/site/contact'
    | '/api/site/health'
    | '/_payload/admin/'
    | '/_site/blog/'
    | '/_site/changelog/'
    | '/_site/projects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PayloadRoute: typeof PayloadRouteWithChildren
  SiteRoute: typeof SiteRouteWithChildren
  HumansDottxtRoute: typeof HumansDottxtRoute
  LlmsFullDottxtRoute: typeof LlmsFullDottxtRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  Char91DotwellKnownChar93SecurityChar91DottxtChar93Route: typeof Char91DotwellKnownChar93SecurityChar91DottxtChar93Route
  ApiSplatRoute: typeof ApiSplatRoute
  ApiSiteChatRoute: typeof ApiSiteChatRoute
  ApiSiteContactRoute: typeof ApiSiteContactRoute
  ApiSiteHealthRoute: typeof ApiSiteHealthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_payload': {
      id: '/_payload'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PayloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site': {
      id: '/_site'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/humans.txt': {
      id: '/humans.txt'
      path: '/humans.txt'
      fullPath: '/humans.txt'
      preLoaderRoute: typeof HumansDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms-full.txt': {
      id: '/llms-full.txt'
      path: '/llms-full.txt'
      fullPath: '/llms-full.txt'
      preLoaderRoute: typeof LlmsFullDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/security.txt': {
      id: '/.well-known/security.txt'
      path: '/.well-known/security.txt'
      fullPath: '/.well-known/security.txt'
      preLoaderRoute: typeof Char91DotwellKnownChar93SecurityChar91DottxtChar93RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site/': {
      id: '/_site/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SiteIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/about': {
      id: '/_site/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof SiteAboutRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/chat': {
      id: '/_site/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof SiteChatRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/contact': {
      id: '/_site/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof SiteContactRouteImport
      parentRoute: typeof SiteRoute
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_payload/admin/': {
      id: '/_payload/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof PayloadAdminIndexRouteImport
      parentRoute: typeof PayloadRoute
    }
    '/_payload/admin/$': {
      id: '/_payload/admin/$'
      path: '/admin/$'
      fullPath: '/admin/$'
      preLoaderRoute: typeof PayloadAdminSplatRouteImport
      parentRoute: typeof PayloadRoute
    }
    '/_site/blog/': {
      id: '/_site/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof SiteBlogIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/blog/$slug': {
      id: '/_site/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof SiteBlogSlugRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/changelog/': {
      id: '/_site/changelog/'
      path: '/changelog'
      fullPath: '/changelog/'
      preLoaderRoute: typeof SiteChangelogIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/changelog/$slug': {
      id: '/_site/changelog/$slug'
      path: '/changelog/$slug'
      fullPath: '/changelog/$slug'
      preLoaderRoute: typeof SiteChangelogSlugRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/projects/': {
      id: '/_site/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof SiteProjectsIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/projects/$slug': {
      id: '/_site/projects/$slug'
      path: '/projects/$slug'
      fullPath: '/projects/$slug'
      preLoaderRoute: typeof SiteProjectsSlugRouteImport
      parentRoute: typeof SiteRoute
    }
    '/api/site/chat': {
      id: '/api/site/chat'
      path: '/api/site/chat'
      fullPath: '/api/site/chat'
      preLoaderRoute: typeof ApiSiteChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/site/contact': {
      id: '/api/site/contact'
      path: '/api/site/contact'
      fullPath: '/api/site/contact'
      preLoaderRoute: typeof ApiSiteContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/site/health': {
      id: '/api/site/health'
      path: '/api/site/health'
      fullPath: '/api/site/health'
      preLoaderRoute: typeof ApiSiteHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PayloadRouteChildren {
  PayloadAdminSplatRoute: typeof PayloadAdminSplatRoute
  PayloadAdminIndexRoute: typeof PayloadAdminIndexRoute
}

const PayloadRouteChildren: PayloadRouteChildren = {
  PayloadAdminSplatRoute: PayloadAdminSplatRoute,
  PayloadAdminIndexRoute: PayloadAdminIndexRoute,
}

const PayloadRouteWithChildren =
  PayloadRoute._addFileChildren(PayloadRouteChildren)

interface SiteRouteChildren {
  SiteAboutRoute: typeof SiteAboutRoute
  SiteChatRoute: typeof SiteChatRoute
  SiteContactRoute: typeof SiteContactRoute
  SiteIndexRoute: typeof SiteIndexRoute
  SiteBlogSlugRoute: typeof SiteBlogSlugRoute
  SiteChangelogSlugRoute: typeof SiteChangelogSlugRoute
  SiteProjectsSlugRoute: typeof SiteProjectsSlugRoute
  SiteBlogIndexRoute: typeof SiteBlogIndexRoute
  SiteChangelogIndexRoute: typeof SiteChangelogIndexRoute
  SiteProjectsIndexRoute: typeof SiteProjectsIndexRoute
}

const SiteRouteChildren: SiteRouteChildren = {
  SiteAboutRoute: SiteAboutRoute,
  SiteChatRoute: SiteChatRoute,
  SiteContactRoute: SiteContactRoute,
  SiteIndexRoute: SiteIndexRoute,
  SiteBlogSlugRoute: SiteBlogSlugRoute,
  SiteChangelogSlugRoute: SiteChangelogSlugRoute,
  SiteProjectsSlugRoute: SiteProjectsSlugRoute,
  SiteBlogIndexRoute: SiteBlogIndexRoute,
  SiteChangelogIndexRoute: SiteChangelogIndexRoute,
  SiteProjectsIndexRoute: SiteProjectsIndexRoute,
}

const SiteRouteWithChildren = SiteRoute._addFileChildren(SiteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  PayloadRoute: PayloadRouteWithChildren,
  SiteRoute: SiteRouteWithChildren,
  HumansDottxtRoute: HumansDottxtRoute,
  LlmsFullDottxtRoute: LlmsFullDottxtRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  Char91DotwellKnownChar93SecurityChar91DottxtChar93Route:
    Char91DotwellKnownChar93SecurityChar91DottxtChar93Route,
  ApiSplatRoute: ApiSplatRoute,
  ApiSiteChatRoute: ApiSiteChatRoute,
  ApiSiteContactRoute: ApiSiteContactRoute,
  ApiSiteHealthRoute: ApiSiteHealthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
