/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PayloadRouteImport } from './routes/_payload'
import { Route as DemoFormRouteImport } from './routes/demo-form'
import { Route as DemoQueryRouteImport } from './routes/demo-query'
import { Route as DemoThemeRouteImport } from './routes/demo-theme'
import { Route as ApiSplatRouteImport } from './routes/api.$'
import { Route as PayloadAdminIndexRouteImport } from './routes/_payload.admin.index'
import { Route as PayloadAdminSplatRouteImport } from './routes/_payload.admin.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PayloadRoute = PayloadRouteImport.update({
  id: '/_payload',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoFormRoute = DemoFormRouteImport.update({
  id: '/demo-form',
  path: '/demo-form',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoQueryRoute = DemoQueryRouteImport.update({
  id: '/demo-query',
  path: '/demo-query',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoThemeRoute = DemoThemeRouteImport.update({
  id: '/demo-theme',
  path: '/demo-theme',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const PayloadAdminIndexRoute = PayloadAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => PayloadRoute,
} as any)
const PayloadAdminSplatRoute = PayloadAdminSplatRouteImport.update({
  id: '/admin/$',
  path: '/admin/$',
  getParentRoute: () => PayloadRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/demo-form': typeof DemoFormRoute
  '/demo-query': typeof DemoQueryRoute
  '/demo-theme': typeof DemoThemeRoute
  '/api/$': typeof ApiSplatRoute
  '/admin/$': typeof PayloadAdminSplatRoute
  '/admin/': typeof PayloadAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/demo-form': typeof DemoFormRoute
  '/demo-query': typeof DemoQueryRoute
  '/demo-theme': typeof DemoThemeRoute
  '/api/$': typeof ApiSplatRoute
  '/admin/$': typeof PayloadAdminSplatRoute
  '/admin': typeof PayloadAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_payload': typeof PayloadRouteWithChildren
  '/demo-form': typeof DemoFormRoute
  '/demo-query': typeof DemoQueryRoute
  '/demo-theme': typeof DemoThemeRoute
  '/api/$': typeof ApiSplatRoute
  '/_payload/admin/$': typeof PayloadAdminSplatRoute
  '/_payload/admin/': typeof PayloadAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/demo-form'
    | '/demo-query'
    | '/demo-theme'
    | '/api/$'
    | '/admin/$'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/demo-form'
    | '/demo-query'
    | '/demo-theme'
    | '/api/$'
    | '/admin/$'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_payload'
    | '/demo-form'
    | '/demo-query'
    | '/demo-theme'
    | '/api/$'
    | '/_payload/admin/$'
    | '/_payload/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PayloadRoute: typeof PayloadRouteWithChildren
  DemoFormRoute: typeof DemoFormRoute
  DemoQueryRoute: typeof DemoQueryRoute
  DemoThemeRoute: typeof DemoThemeRoute
  ApiSplatRoute: typeof ApiSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_payload': {
      id: '/_payload'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PayloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo-form': {
      id: '/demo-form'
      path: '/demo-form'
      fullPath: '/demo-form'
      preLoaderRoute: typeof DemoFormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo-query': {
      id: '/demo-query'
      path: '/demo-query'
      fullPath: '/demo-query'
      preLoaderRoute: typeof DemoQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo-theme': {
      id: '/demo-theme'
      path: '/demo-theme'
      fullPath: '/demo-theme'
      preLoaderRoute: typeof DemoThemeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_payload/admin/': {
      id: '/_payload/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof PayloadAdminIndexRouteImport
      parentRoute: typeof PayloadRoute
    }
    '/_payload/admin/$': {
      id: '/_payload/admin/$'
      path: '/admin/$'
      fullPath: '/admin/$'
      preLoaderRoute: typeof PayloadAdminSplatRouteImport
      parentRoute: typeof PayloadRoute
    }
  }
}

interface PayloadRouteChildren {
  PayloadAdminSplatRoute: typeof PayloadAdminSplatRoute
  PayloadAdminIndexRoute: typeof PayloadAdminIndexRoute
}

const PayloadRouteChildren: PayloadRouteChildren = {
  PayloadAdminSplatRoute: PayloadAdminSplatRoute,
  PayloadAdminIndexRoute: PayloadAdminIndexRoute,
}

const PayloadRouteWithChildren =
  PayloadRoute._addFileChildren(PayloadRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PayloadRoute: PayloadRouteWithChildren,
  DemoFormRoute: DemoFormRoute,
  DemoQueryRoute: DemoQueryRoute,
  DemoThemeRoute: DemoThemeRoute,
  ApiSplatRoute: ApiSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
